<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>
  <ItemGroup>
    <!-- nulic -->
    <PackageVersion Include="AngleSharp" Version="1.4.0" />
    <PackageVersion Include="F23.StringSimilarity" Version="7.0.1" />
    <PackageVersion Include="Microsoft.Build" Version="18.6.3" />
    <PackageVersion Include="MinVer" Version="6.0.0" />
    <PackageVersion Include="NuGet.Commands" Version="7.6.0" />
    <PackageVersion Include="Serilog.Sinks.Console" Version="6.1.1" />
    <PackageVersion Include="System.CommandLine" Version="2.0.8" />
    <PackageVersion Include="Textify" Version="0.2.0-beta" />
    <!-- unit_tests -->
    <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="18.5.1" />
    <PackageVersion Include="MSTest.TestAdapter" Version="4.2.3" />
    <PackageVersion Include="MSTest.TestFramework" Version="4.2.3" />
    <PackageVersion Include="coverlet.collector" Version="10.0.0" />
    <PackageVersion Include="NuGet.Packaging" Version="7.6.0" />
    <!-- testprojects -->
    <PackageVersion Include="PdfSharpCore" Version="1.3.67" />
    <PackageVersion Include="SixLabors.ImageSharp" Version="3.1.12" />
  </ItemGroup>
</Project>