<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AngleSharp" />
    <PackageReference Include="F23.StringSimilarity" />
    <PackageReference Include="Microsoft.Build" />
    <PackageReference Include="NuGet.Commands" />
    <PackageReference Include="Serilog.Sinks.Console" />
    <PackageReference Include="System.CommandLine" />
    <PackageReference Include="Textify" />
  </ItemGroup>

</Project>